[global]

[hasura]
version = 'v2.36.9-ce'
adminSecret = '{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
webhookSecret = '{{ secrets.NHOST_WEBHOOK_SECRET }}'

[[hasura.jwtSecrets]]
type = 'HS256'
key = '{{ secrets.HASURA_GRAPHQL_JWT_SECRET }}'

[hasura.settings]
corsDomain = ['*']
devMode = true
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false
enabledAPIs = ['metadata', 'graphql', 'pgdump', 'config']

[hasura.logs]
level = 'warn'

[hasura.events]
httpPoolSize = 100

[functions]
[functions.node]
version = 22

[auth]
version = '0.37.1'

[auth.redirections]
clientUrl = 'https://sunfall.netlify.app/'
allowedUrls = ['https://sunfall.netlify.app/change-password']

[auth.signUp]
enabled = true

[auth.user]
[auth.user.roles]
default = 'user'
allowed = ['user', 'me']

[auth.user.locale]
default = 'en'
allowed = ['en']

[auth.user.gravatar]
enabled = true
default = 'identicon'
rating = 'g'

[auth.user.email]

[auth.user.emailDomains]

[auth.session]
[auth.session.accessToken]
expiresIn = 900

[[auth.session.accessToken.customClaims]]
key = 'user-displayName'
value = 'displayName'

[[auth.session.accessToken.customClaims]]
key = 'user-email'
value = 'email'

[[auth.session.accessToken.customClaims]]
key = 'organization-id'
value = 'metadata.defaultOrganizationId'

[[auth.session.accessToken.customClaims]]
key = 'organization-ids'
value = 'user_organizations[*].organization_id'

[[auth.session.accessToken.customClaims]]
key = 'project-ids'
value = 'user_projects.project_id[]'

[auth.session.refreshToken]
expiresIn = 43200

[auth.method]
[auth.method.anonymous]
enabled = false

[auth.method.emailPasswordless]
enabled = false

[auth.method.emailPassword]
hibpEnabled = false
emailVerificationRequired = true
passwordMinLength = 9

[auth.method.smsPasswordless]
enabled = false

[auth.method.oauth]
[auth.method.oauth.apple]
enabled = false

[auth.method.oauth.azuread]
tenant = 'common'
enabled = false

[auth.method.oauth.bitbucket]
enabled = false

[auth.method.oauth.discord]
enabled = false

[auth.method.oauth.facebook]
enabled = false

[auth.method.oauth.github]
enabled = false

[auth.method.oauth.gitlab]
enabled = false

[auth.method.oauth.google]
enabled = false

[auth.method.oauth.linkedin]
enabled = false

[auth.method.oauth.spotify]
enabled = false

[auth.method.oauth.strava]
enabled = false

[auth.method.oauth.twitch]
enabled = false

[auth.method.oauth.twitter]
enabled = false

[auth.method.oauth.windowslive]
enabled = false

[auth.method.oauth.workos]
enabled = false

[auth.method.webauthn]
enabled = false

[auth.method.webauthn.attestation]
timeout = 60000

[auth.totp]
enabled = false

[postgres]
version = '14.15-20250311-1'

[postgres.resources]
[postgres.resources.storage]
capacity = 1

[provider]

[storage]
version = '0.6.1'

[observability]
[observability.grafana]
adminPassword = '{{ secrets.GRAFANA_ADMIN_PASSWORD }}'
